from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
from typing import Any, Mapping

from drive_evidence_adapter import adapt_drive_evidence_payload
from evidence_gate import classify_payload
from github_workflow_adapter import adapt_github_workflow_payload


RUNNER_VERSION = "unified-evidence-source-runner-v1"
ENGINE_GITHUB_BLOB_SHA1 = "db1a76aff157bef09fc7b13d7dbda490a9ef1016"


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        )
        + "\n"
    ).encode("utf-8")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(
        f"blob {len(data)}\0".encode("utf-8") + data
    ).hexdigest()


def detect_source_type(payload: Mapping[str, Any]) -> str:
    explicit = payload.get("source_type")
    if explicit is not None and explicit not in {
        "github_workflows",
        "google_drive",
    }:
        raise ValueError(
            "source_type must be 'github_workflows' or 'google_drive'"
        )

    github_shape = all(
        key in payload
        for key in (
            "repository",
            "head_sha",
            "required_workflows",
            "workflow_runs",
        )
    )
    drive_shape = all(
        key in payload
        for key in (
            "scope_name",
            "required_artifacts",
            "drive_records",
        )
    )

    if github_shape and drive_shape:
        raise ValueError(
            "ambiguous input: matches both GitHub and Google Drive shapes"
        )

    detected = None
    if github_shape:
        detected = "github_workflows"
    elif drive_shape:
        detected = "google_drive"

    if explicit is not None:
        if detected is not None and explicit != detected:
            raise ValueError(
                f"source_type={explicit} conflicts with detected shape={detected}"
            )
        detected = explicit

    if detected is None:
        raise ValueError("unable to auto-select adapter from input shape")

    return detected


def adapt_source(
    payload: Mapping[str, Any],
) -> tuple[str, dict[str, Any]]:
    source_type = detect_source_type(payload)
    if source_type == "github_workflows":
        return source_type, adapt_github_workflow_payload(payload)
    return source_type, adapt_drive_evidence_payload(payload)


def run_unified(
    payload: Mapping[str, Any],
) -> tuple[dict[str, Any], dict[str, Any]]:
    source_type, adapted = adapt_source(payload)
    classification = classify_payload(adapted)

    result = {
        "runner": RUNNER_VERSION,
        "source_type": source_type,
        "adapter": adapted["adapter"]["name"],
        "adapter_policy_version": adapted["adapter"]["policy_version"],
        "classification": classification.to_dict(),
    }

    engine_bytes = Path(__file__).with_name("evidence_gate.py").read_bytes()
    engine_blob = git_blob_sha1(engine_bytes)

    receipt = {
        "runner": RUNNER_VERSION,
        "execution_status": "PASS",
        "source_type": source_type,
        "adapter": adapted["adapter"]["name"],
        "adapter_policy_version": adapted["adapter"]["policy_version"],
        "engine_github_blob_sha1_expected": ENGINE_GITHUB_BLOB_SHA1,
        "engine_local_git_blob_sha1": engine_blob,
        "engine_identity_pass": engine_blob == ENGINE_GITHUB_BLOB_SHA1,
        "input_sha256": sha256_bytes(canonical_json_bytes(payload)),
        "adapted_input_sha256": sha256_bytes(
            canonical_json_bytes(adapted)
        ),
        "result_sha256": sha256_bytes(canonical_json_bytes(result)),
        "classification_status": classification.status.value,
        "supporting_count": classification.supporting_count,
        "contradicting_count": classification.contradicting_count,
        "insufficient_count": classification.insufficient_count,
        "claim": classification.claim,
        "claim_ceiling": (
            "Only the narrow claim generated by the selected source adapter. "
            "No runtime admission, production readiness, certification, "
            "merge readiness, or global validity is implied."
        ),
    }

    return result, receipt


def _atomic_write_json(path: Path, value: Any) -> None:
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(
        json.dumps(
            value,
            indent=2,
            sort_keys=True,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    os.replace(tmp, path)


def default_paths(input_path: Path) -> tuple[Path, Path]:
    stem = input_path.with_suffix("")
    return (
        stem.with_name(stem.name + ".result.json"),
        stem.with_name(stem.name + ".receipt.json"),
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Auto-select GitHub or Drive adapter, run Evidence Gate, "
            "and write one result plus one receipt."
        )
    )
    parser.add_argument("input", type=Path)
    parser.add_argument("--result", type=Path)
    parser.add_argument("--receipt", type=Path)
    args = parser.parse_args()

    result_path, receipt_path = default_paths(args.input)
    result_path = args.result or result_path
    receipt_path = args.receipt or receipt_path

    try:
        payload = json.loads(args.input.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise ValueError("input JSON must contain an object")
        result, receipt = run_unified(payload)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        _atomic_write_json(
            receipt_path,
            {
                "runner": RUNNER_VERSION,
                "execution_status": "ERROR",
                "error_type": type(exc).__name__,
                "error": str(exc),
                "result_written": False,
            },
        )
        parser.error(str(exc))

    _atomic_write_json(result_path, result)
    receipt = {
        **receipt,
        "result_file": str(result_path),
        "receipt_file": str(receipt_path),
    }
    _atomic_write_json(receipt_path, receipt)

    print(
        json.dumps(
            {
                "source_type": result["source_type"],
                "status": result["classification"]["status"],
                "result_file": str(result_path),
                "receipt_file": str(receipt_path),
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
